apiVersion: v1
kind: Service
metadata:
  labels:
    app: ols
    service: ols-web
  name: ols-web
spec:
  ports:
    - name: "ols-web"
      port: 8080
      targetPort: 8080
  selector:
    service: ols-web
#  type: LoadBalancer
