apiVersion: v1
kind: Service
metadata:
  labels:
    app: ols
    service: solr
  name: solr
spec:
  ports:
    - name: "solr"
      port: 8983
      targetPort: 8983
  selector:
    service: solr
 # type: LoadBalancer
